export const GET_BLOGS_REQUEST = 'GET_BLOGS_REQUEST';
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_FAIL = 'GET_BLOGS_FAIL';

export const GET_MORE_BLOGS_REQUEST = 'GET_MORE_BLOGS_REQUEST';
export const GET_MORE_BLOGS_SUCCESS = 'GET_MORE_BLOGS_SUCCESS';
export const GET_MORE_BLOGS_FAIL = 'GET_MORE_BLOGS_FAIL';

export const BLOG_DETAILS_REQUEST = 'BLOG_DETAILS_REQUEST';
export const BLOG_DETAILS_SUCCESS = 'BLOG_DETAILS_SUCCESS';
export const BLOG_DETAILS_FAIL = 'BLOG_DETAILS_FAIL';
export const CLEAR_BLOG_DETAILS = 'CLEAR_BLOG_DETAILS';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const ADD_COMMENT_RESET = 'ADD_COMMENT_RESET';

export const GET_COMMENT_REQUEST = 'GET_COMMENT_REQUEST';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAIL = 'GET_COMMENT_FAIL';

export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAIL = 'DELETE_BLOG_FAIL';
export const DELETE_BLOG_RESET = 'DELETE_BLOG_RESET';

export const INCREASE_VIEWS_COUNT_SUCCESS = 'INCREASE_VIEWS_COUNT_SUCCESS';
export const INCREASE_VIEWS_COUNT_FAIL = 'INCREASE_VIEWS_COUNT_FAIL';
export const INCREASE_VIEWS_COUNT_RESET = 'INCREASE_VIEWS_COUNT_RESET';

export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const LIKE_FAIL = 'LIKE_FAIL';
export const LIKE_RESET = 'LIKE_RESET';

export const GET_LIKES_SUCCESS = 'GET_LIKES_SUCCESS';
export const GET_LIKES_FAIL = 'GET_LIKES_FAIL';

export const NEW_BLOG_REQUEST = 'NEW_BLOG_REQUEST';
export const NEW_BLOG_SUCCESS = 'NEW_BLOG_SUCCESS';
export const NEW_BLOG_FAIL = 'NEW_BLOG_FAIL';
export const NEW_BLOG_RESET = 'NEW_BLOG_RESET';

export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAIL = 'UPDATE_BLOG_FAIL';
export const UPDATE_BLOG_RESET = 'UPDATE_BLOG_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
