export const GET_BLOGS_REQUEST = 'GET_BLOGS_REQUEST';
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_FAIL = 'GET_BLOGS_FAIL';

export const GET_MORE_BLOGS_REQUEST = 'GET_MORE_BLOGS_REQUEST';
export const GET_MORE_BLOGS_SUCCESS = 'GET_MORE_BLOGS_SUCCESS';
export const GET_MORE_BLOGS_FAIL = 'GET_MORE_BLOGS_FAIL';

export const BLOG_DETAILS_REQUEST = 'BLOG_DETAILS_REQUEST';
export const BLOG_DETAILS_SUCCESS = 'BLOG_DETAILS_SUCCESS';
export const BLOG_DETAILS_FAIL = 'BLOG_DETAILS_FAIL';
export const CLEAR_BLOG_DETAILS = 'CLEAR_BLOG_DETAILS';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const ADD_COMMENT_RESET = 'ADD_COMMENT_RESET';

export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAIL = 'DELETE_BLOG_FAIL';
export const DELETE_BLOG_RESET = 'DELETE_BLOG_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';