# Generated by Django 4.0.2 on 2022-03-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updateDate',
            new_name='updatedDate',
        ),
    ]
